---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdetails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdetails-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: productdetails-app
    spec:
      containers:
        - name: productdetails-app
          image: samadhangapat/productdetailsms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: prdms-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prdms-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prdms-secret
                  key: SPRING_DATASOURCE_PASSWORD

      restartPolicy: Always

...